// Bundled offline translations for FINITE generated-content strings — the term
// names, knowledge phrases and labeled reading lines whose set is fixed and small
// enough to ship inside the app. Looking these up is synchronous, instant, and
// works with no network, so localized generated content renders on first paint
// with no English flash.
//
// This is the "template-level" half of the localization hybrid: finite content is
// pre-translated and bundled here; combinatorial flowing prose (daily/weekly
// horoscopes) is left to the runtime translate path in i18nContent.ts.
//
// The map is generated by scripts/i18n/gen_content_bundle.py. English is the
// identity (never stored). Missing entries simply fall through to English (or, in
// i18nContent, to the runtime translation), so the app never breaks.

import raw from '@/i18n/generatedContent.json';

// `raw` includes a `_meta` block, so cast through `unknown`; only real language
// keys (hi/mr/kn/ta/te) are ever read, never `_meta`.
const BUNDLE = raw as unknown as Record<string, Record<string, string>>;
const SUPPORTED = new Set(['hi', 'mr', 'kn', 'ta', 'te']);

/** Localized string for `en` in `lang` from the offline bundle, or null if absent. */
export function bundleGet(lang: string, en: string): string | null {
  if (!SUPPORTED.has(lang) || typeof en !== 'string') return null;
  const m = BUNDLE[lang];
  const v = m ? m[en] : undefined;
  return typeof v === 'string' && v.length > 0 ? v : null;
}

/** Map a list through the bundle (unbundled items pass through unchanged). */
export function localizeFromBundle(texts: string[], lang: string): string[] {
  if (!SUPPORTED.has(lang)) return texts.slice();
  return texts.map((t) => (typeof t === 'string' ? bundleGet(lang, t) ?? t : t));
}

/** How many strings are bundled for a language (for diagnostics/tests). */
export function bundleSize(lang: string): number {
  return BUNDLE[lang] ? Object.keys(BUNDLE[lang]).length : 0;
}
